### ISSUE TITLE
Unable to run application

### ISSUE THREAD

**Issue by bayleedev** [pahgawk/Electioneering#18]
After running grunt it mentioned I needed to install `sass` and `sinatra`:

```
gem install sass
gem install sinatra
```

The web request mentions I am missing a `map.svg` file.

Related items:
https://github.com/davepagurek/Electioneering/blob/master/server.rb#L4
https://github.com/davepagurek/Electioneering/tree/master/public/data

**Comment by davepagurek** [comment]
@trishume `ruby script/mapgen.rb` and `ruby script/peoplegen.rb` also need to be run if I recall correctly, right? we should update the readme

**Comment by trishume** [comment]
Yah currently the process to run this is undocumented and bad.
It goes something like

```
$ bundle install
$ npm install
$ bower install
$ ruby script/mapgen.rb
$ ruby script/peoplegen.rb
$ grunt
```

Hackathons ¯\_(ツ)_/¯

I plan on adding a `default.nix` file soon so that you can instantly get it working with the Nix package manager, and also plan on using that to host it on my VPS.
